services:
  db:
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mqtt:
    image: hivemq/hivemq4
    ports:
      - "1883:1883"    # MQTT protocol
      - "8883:8883"    # TLS Port
      - "8080:8080"    # HiveMQ Web UI (optional)
    restart: unless-stopped
    
  app:
    build:
      context: ./  
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"  
    depends_on:
      - db
      - mqtt
  
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/scripts:/scripts
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    entrypoint: ["/bin/bash", "/scripts/entrypoint.sh"]
    environment:
      TLS_CERT_B64: ${TLS_CERT_B64}
      TLS_KEY_B64: ${TLS_KEY_B64}



volumes:
  postgres_data:
