services:
  db:
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mqtt:
    image: hivemq/hivemq4
    ports:
      - "1883:1883"    # MQTT protocol
      - "8883:8883"    # TLS Port
      - "8080:8080"    # HiveMQ Web UI (optional)
    restart: unless-stopped
    
  app:
    build:
      context: ./  # or ./backend if Dockerfile is there
      dockerfile: Dockerfile
    #env_file:
    #  - ./local.env
    ports:
      - "5000:80"  # exposes app externally
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PgDbConnection=Host=db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}
      - MQTT_BROKER=mqtt
      - Cloudinary__CloudName=${CLOUDINARY_CLOUDNAME}
      - Cloudinary__ApiKey=${CLOUDINARY_APIKEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_APISECRET}
    depends_on:
      - db
      - mqtt



volumes:
  postgres_data:
