name: Deploy to Cloud

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_USER }}
          key: ${{ secrets.CLOUD_SSH_KEY }}
          source: "."  # Adjust to only what's needed if project is big
          target: "my-iot-app/"
          rm: true


      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_USER }}
          key: ${{ secrets.CLOUD_SSH_KEY }}
          script: |
            cd my-iot-app
            
            # Export secrets into current shell so docker-compose can use them
            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
            export MQTT_BROKER="${{ secrets.MQTT_BROKER }}"
            export CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}"
            export CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}"
            export CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}"
            
            docker compose down || true
            docker compose up -d --build